# Config file for Misbehaviour Detector

# MBD has internal default values equal to the ones used in this file
# Remove the # in front of each line and change value to customize the configuration

# General options for some calculations of detection
[OPTIONS]
    # If this option is true position related checks Haversine distance formula will be used instead of Euclidean formula
    # UseHaversine = false

    # Set the tolerance % to be used in checks
    # This tolerance doesn't apply to threshold checks but to inconsistency checks so low tolerances may result in constant detections
    # Tolerance = 10

    # Set the maximum time in seconds that can pass before two messages are not considered consecutive for inconsistency checks
    MaxTimeForConsecutive = 1.0

    # If this option is true security checks are ignored
    # IgnoreSecurity = false

    # This changes the size of sectors in the OSM data map
    # MaxSectorSize = 250

    # Set the amount the base tolerance is multiplied to allow for less strict checks on CPMs, values above 1 allow more tolerance
    # ToleranceMultiplierCPM = 1.5

    # Set the API Key for the meteoblue
    # weatherAPIKey = 


# ABOUT THRESHOLDS
# The units used for thresholds are the same for general and station type specific and are the following:
    # MaxSpeed : [km/h] kilometer per hour
    # MaxAcceleration : [m/s^2] meter per squared second
    # MaxBraking : [m/s^2] meter per squared second
    # MaxCurvature : [m^-1] 1 over 10000 meter
    # MaxYawRate : [°/s] degree per second
    # MaxJerk : [m/s^3] meter per cubed second

# General thresholds are the defaults used on every stationType if no stationType specific threshold is set
[GENERAL_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

# ------- STATION TYPE SPECIFIC THRESHOLDS -------

[BUS_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[CYCLIST_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[PASSENGER_CAR_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[PEDESTRIAN_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[TRUCK_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[HEAVY_TRUCK_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[LIGHT_TRUCK_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[MOPED_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[MOTORCYCLE_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[PASSENGER_CAR_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[PEDESTRIAN_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[RSU_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[SPECIAL_VEHICLES_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[TRAILER_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[TRAM_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[LIGHT_VRU_VEHICLE_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[ANIMAL_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6

[AGRICULTURAL_THRESHOLDS]
    # MaxSpeed = 380
    # MaxAcceleration = 20
    # MaxBraking = -50
    # MaxCurvature = 50
    # MaxYawRate = 50
    # MaxJerk = 6